### ISSUE TITLE
Inspec test for orchestrator not working

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-provisioner#70]
The inspec test for the orchestrator is not working and gives following error message:

```
Testing orchestrator component using InSpec...
/opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib/rspec
/core/example_group.rb:725:in `method_missing': `os` is not available on an example group (e.g. a 
`describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or 
from constructs that run in the scope of an example (e.g. `before`, `let`, etc). 
(RSpec::Core::ExampleGroup::WrongScopeError)
	from orchestrator_spec.rb:4:in `block in load_with_context'
[...]
```

**Comment by cliffano** [comment]
Done. To be included in 2.4.16 .
