### ISSUE TITLE
Chaos Monkey spec test can't find lookup

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-provisioner#82]
Chaos Monkey provisioning currently completes as expected, however, the spec test is failing with the following error:

```
> /opt/puppetlabs/puppet/bin/inspec exec chaos-monkey_spec.rb
chaos-monkey_spec.rb:3:in `load_with_context': undefined method `lookup' for nil:NilClass (NoMethodError)
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile_context.rb:157:in `instance_eval'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile_context.rb:157:in `load_with_context'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile_context.rb:141:in `load_control_file'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile.rb:167:in `block in collect_tests'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile.rb:164:in `each'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/profile.rb:164:in `collect_tests'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/runner.rb:93:in `block in load'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/runner.rb:82:in `each'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/runner.rb:82:in `load'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/runner.rb:103:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/lib/inspec/cli.rb:174:in `exec'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /opt/puppetlabs/puppet/lib/ruby/gems/2.4.0/gems/inspec-1.51.6/bin/inspec:12:in `<top (required)>'
	from /opt/puppetlabs/puppet/bin/inspec:23:in `load'
	from /opt/puppetlabs/puppet/bin/inspec:23:in `<main>'
```

**Comment by cliffano** [comment]
Fixed. To be included in v2.4.17 .
